### PR TITLE
Improve PEP 8 conformance of generated code.

### PR DESCRIPTION
**Pull request by techdragon**
- Removed blank line that was introducing too many spaces between classes in the operations block.

### CODE REVIEW

**Comment by pope1ni** [comment]
We'll have to think about this one. I spent quite a while trying to get this right, but I think that it is somewhat impossible while soapfish uses templates to generate code. One change to fix white space seems to unfix another attempt to resolve the problem code generated by a different WSDL.

**Comment by techdragon** [comment]
@pope1ni I agree that the code generation is tricky, I'm still formatting up a larger change to the generation template to fix #97 and part of getting that as concise as possible made it seem like a good idea to separate out any 'other' fixes into their own changes. 

Since the test cases did pass, I'm curious if there is any hesitation about this particular line of whitespace, or wether its an overall (and understandable) need for caution when making changes to the code generation templates.

**Comment by pope1ni** [comment]
I think that I have actually already dealt with this one recently, but by removing a different line:

https://github.com/soapteam/soapfish/commit/4744fa3eb111fda439b10679d9b3a1e1b35816d1#diff-636588725eabc5a0e8aee1288db90ad6L27

I wouldn't particularly trust our test cases at the moment - a lot of work needs to be done here. I think that some tests are obsolete, some are duplicates, some are lacking proper/enough assertions and coverage is only ~88%.

Please close this if you think that my existing change resolves this. Thanks.

**Comment by techdragon** [comment]
I'm closing it for now since its so small and theres much work to be done on more robust code generation, worrying about a few newlines in the old code, when I'm trying to write a new code generator feels rather silly.

**Pull request closed without merging**
