### PR TITLE
Tidy with flake8

### PR DESCRIPTION
**Pull request by funkybob**
I've just tidied some of the code using flake8 feedback, which also helped uncover a bug which I will detail in an issue of its own.

NB I've set the maximum line width to 119 instead of 79... since we don't use Hollerith cards these days :)

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
Thank you very much for your contribution. I just pulled a lot of Nick Pope so of course your patch set doesn't apply anymore (sorry for that but 59 commits trump 4 :-).

I see that you have two commits which are very similar to Nick's commits (remove compat module, drop Python 2.6). I already told Nick that I think we should keep supporting Python 2.6 for the next years (RHEL 6) so I will revert that change very likely.

There are a few nitpicks I have. These are purely personal preferences and don't have any objective basis so please take with a grain of salt - no hard feelings from my side:
 - 2 empty lines between "__all__" and a class declaration seems to be excessive.
 - No sure about the maximum line length. In general I think ~120 chars are fine but I prefer to wrap some lines (mostly function declarations) much earlier.
 - Also "value is False" seems strange. I mean I get it "False" is something like a singleton but "False" is also 0 so personally I prefer "== False/True".
 - why replacing short lambda functions like `is_extension = lambda obj, base: (obj == base)`?

Also before just applying flake8 I think we (@soapteam/soapfish-committers) should come to an agreement if we want to enforce a particular style before just merging stylistic changes like this (otherwise I fear we get some useless code churn due to automated tools fighting each other).

**Comment by pope1ni** [comment]
Hi @funkybob 

You've made many changes that were already in my improvements branch - sorry for the unfortunate timing. Is there any chance that you could rebase this against master for us? That would help us to look through the remaining changes...

Thanks.

**Comment by funkybob** [comment]
I've rebased against master.

To address other comments:
- 2 empty lines between "all" and a class declaration seems to be excessive.

This is PEP8 default.

- Also "value is False" seems strange. I mean I get it "False" is something like a singleton but "False" is also 0 so personally I prefer "== False/True".

Well, "if not value:" would be my preferred, but I didn't look at the code close enough to check if it may be a falsey value...

- why replacing short lambda functions like is_extension = lambda obj, base: (obj == base)?

Again, flake8 recommends to not do that.  If it's a lambda you use once, put it in place.  If not, you might as well use a def'd function.

As to defining your own style guide, PEP8 actually recommends that :)

**Comment by pope1ni** [comment]
Hi. I haven't forgotten about this, but am currently tied up for the next few days and unable to properly review this. Thanks for the two changes regarding the set literal removal - we still need to support Python 2.6 - and the duplicate test file removal - these were moved into `tests/generation`.

Please can you also remove `tests/django_test.py` and `tests/flask_test.py` as they were moved into `tests/framework`.  I'll try and review the remainder later this week.

**Comment by funkybob** [comment]
So the remaining failures are because I converted to using importlib...

**Comment by pope1ni** [comment]
Squashed and merged in 9dd4497. Thanks @funkybob!

Additional cleanups in 0f44362 and restored support for Python 2.6 in 364af26.

**Pull request closed without merging**
